type Mutation {
  """
  Called when user signs in
  """
  generateNonce(address: String!): NonceResponse
  """
  Expects publicAddress and signature to verify if this publicAddress has signed the correct nonce
  """
  verifySignature(input: SignatureVerificationInput!): VerificationResponse
  """
  Create invoice
  """
  createInvoice(input: CreateInvoiceInput!): ApiResponse
  """
  Update invoice
  """
  updateInvoiceTransaction(input: InvoiceTransactionInput!, where: UpdateWhereId!): UpdateResponse
}
