version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - ./data:/var/jenkins_home
    networks:
      - jenkins_network
    ports:
      - 8080:8080

networks:
  jenkins_network:
